# Generated by Django 4.2.24 on 2025-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25, unique=True)),
                ('Email', models.EmailField(max_length=25)),
                ('Password', models.CharField(max_length=30)),
                ('RePassword', models.CharField(max_length=30)),
            ],
        ),
    ]
