# Generated by Django 4.2.24 on 2025-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(default='', max_length=50)),
                ('Image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='validation',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
