# Generated by Django 4.2.24 on 2025-09-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0002_image_alter_validation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
