# Generated by Django 4.2.24 on 2025-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0004_alter_image_caption_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=255, upload_to='img/')),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('genre', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('trailer_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
