# Generated by Django 4.2.24 on 2025-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0005_movies_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='caption',
            field=models.TextField(),
        ),
    ]
