# Generated by Django 4.2.24 on 2025-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0006_alter_movies_actors_alter_movies_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
