# Generated by Django 4.2.24 on 2025-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0007_remove_movies_trailer_url_movies_trailer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='trailer_name',
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
