# Generated by Django 4.2.24 on 2025-10-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0008_remove_movies_trailer_name_movies_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='caption',
            new_name='description',
        ),
    ]
