# Generated by Django 4.2.24 on 2025-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0009_rename_caption_movies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(default='Tamil', max_length=50),
        ),
    ]
