# Generated by Django 4.2.24 on 2025-10-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0010_movies_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
