# Generated by Django 4.2.24 on 2025-10-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0011_movies_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='RePassword',
        ),
    ]
