# Generated by Django 4.2.24 on 2025-10-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp4', '0012_remove_validation_repassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='Username',
        ),
    ]
